---
title: "PCA- Python to R code"
author: "Rafia Amin Raka"
date: "2025-08-13"
output: pdf_document
---


```{r}
# install.packages("corrr")
# install.packages("ggcorrplot")
# install.packages("FactoMineR")
# install.packages("factoextra")
# install.packages("broom")

library(ggplot2)
library(corrr)
library(ggcorrplot)
library(FactoMineR)
library(factoextra)
library(broom)
```

```{r}
data <- data.frame( Height = c(170, 165, 180, 175, 160, 172, 168, 177, 162, 158),
  Weight = c(65, 59, 75, 68, 55, 70, 62, 74, 58, 54),
  Age = c(30, 25, 35, 28, 22, 32, 27, 33, 24, 21),
  Gender = c(1, 0, 1, 1, 0, 1, 0, 1, 0, 0)
)
print(data)
```
```{r}
numerical_data <- data[, c("Height", "Weight", "Age", "Gender")]
head(numerical_data)
data_normalized <- scale(numerical_data)
head(data_normalized)
data.pca <- princomp(data_normalized)
summary(data.pca)
```

```{r}
data.pca$loadings[, 1:2]
fviz_eig(data.pca, addlabels = TRUE)
fviz_pca_var(data.pca, col.var = "black")
fviz_cos2(data.pca, choice = "var", axes = 1:2)
fviz_pca_var(data.pca, col.var = "cos2", gradient.cols = c("black", "yellow", "seagreen"), repel = TRUE)

```

